### ISSUE TITLE
Prefix all vim helpfile tags

### ISSUE THREAD

**Issue by kiryph** [dawikur/algorithm-mnemonics.vim#2]
Vim's documentation http://vimhelp.appspot.com/helphelp.txt.html#help-writing says

> The tag-name should be different from all the Vim help tag names and ideally
> should begin with the name of the Vim plugin.

Since the plugin name is too long, I would consider a different prefix following common rules:

For instance, [vim-latex](https://github.com/vim-latex/vim-latex/blob/master/doc/latexhelp.txt) includes a latex-help.txt file with the tag prefix `latex-`.

http://vimhelp.appspot.com/filetype.txt.html#ftplugin-docs would suggest something like
   `ft-cpp-snippets-stl-`

Examples from http://vimhelp.appspot.com/filetype.txt.html#filetypes

> [...] To search for help on a filetype prepend "ft-" and optionally append
>  "-syntax", "-indent" or
> "-plugin".  For example:
>   :help ft-vim-indent
>   :help ft-vim-syntax
>   :help ft-man-plugin

Note, the help command matches partials `:h partial`. You can still open with `:h partial_sort_copy` but `:h stl-copy` would open the description of the stl-snippet, but with `:h copy` you get the default vim help.

**Comment by dawikur** [comment]
I did prefixed helpfile tags with plugin name, even if it is quite long (now when I think about it... plugin name should probably contain `cpp`. Will see, for now it is probably good to leave it as close to original repo-name as possible).

In vim it is actual not so big issue as you can use tab-expansion: `:h algo<tab>` and it expands full name.

@kiryph  What do you think?

**Comment by kiryph** [comment]
I think using your plugin name is perfectly fine. Most importantly the tag names have to be unique w.r.t. the builtin help tags.

Adding cpp would be sensible, since there might be someone doing the same for a different language.

Naming things is usually a matter of personal choice, following certain common schemes and being constraint by things you cannot change. There is usually no perfect answer, but one can still try to choose wisely.
